services:
  db:
    image: postgres:16
    container_name: quiz-db
    environment:
      POSTGRES_DB: quizdb
      POSTGRES_USER: quiz
      POSTGRES_PASSWORD: quiz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quiz -d quizdb"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
