# Generated by Django 5.2.7 on 2025-10-06 01:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizsession',
            name='mp_payment_id',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='mp_pref_id',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='quizsession',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='quizsession',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='quizapp.quiz'),
        ),
        migrations.AlterField(
            model_name='quizsession',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
