# Generated by Django 5.2.7 on 2025-10-06 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_remove_quizsession_mp_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizsession',
            name='mp_pref_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
