# Generated by Django 5.2.7 on 2025-10-09 23:55

import quizapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_quizsession_mp_pref_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=quizapp.models.quiz_cover_path),
        ),
    ]
